service: imaginess

frameworkVersion: '2'

useDotenv: true

provider:
  name: azure
  region: westeurope
  runtime: nodejs12
  environment:
    COSMOS_ENDPOINT: ${env:COSMOS_ENDPOINT}
    COSMOS_KEY: ${env:COSMOS_KEY}
    BLOB_STORAGE_CONNECTION_STRING: ${env:BLOB_STORAGE_CONNECTION_STRING}

plugins: # look for additional plugins in the community plugins repo: https://github.com/serverless/plugins
  - serverless-azure-functions

package:
  exclude:
    - .vscode/**
    - src/**
    - local.settings.json
    - serverless.template.yml
    - README.md
    - .prettierignore
    - .prettierrc
    - .eslintrc.json

functions:
  createBlob:
    handler: dist/handlers/createBlob
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous

  createImage:
    handler: dist/handlers/createImage
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous

  getRandomImage:
    handler: dist/handlers/getRandomImage
    events:
      - http: true
        methods:
          - GET
        authLevel: anonymous